project_name: k8s-find-outdated-images
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
dockers:
  - image_templates:
      - nniikkoollaaii/k8s-find-outdated-images:latest
      - nniikkoollaaii/k8s-find-outdated-images:v{{ .Major }}
      - nniikkoollaaii/k8s-find-outdated-images:{{ .Tag }}
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - nniikkoollaaii/k8s-find-outdated-images:latest
      - nniikkoollaaii/k8s-find-outdated-images:v{{ .Major }}
      - nniikkoollaaii/k8s-find-outdated-images:{{ .Tag }}
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

# release:
#   github:
#     owner: user
#     name: repo



# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
