on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Test


env:
  KIND_CLUSTER_NAME: "cluster"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
          cache: true
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
        
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}


      - uses: azure/setup-kubectl@v3
        name: Install kubectl
        
      - name: Run test setup script
        run: |
          chmod +x ./test/test_setup.sh
          ./test/test_setup.sh
        shell: bash

      - name: Run test script
        run: |
          chmod +x ./test/test.sh
          ./test/test.sh ${KIND_CLUSTER_NAME}
        shell: bash

      - name: Check test result
        run: |
          chmod +x ./test/test_check.sh
          ./test/test_check.sh
        shell: bash