on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        #go-version: [1.18.x, 1.19.x]
        #os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      name: "Set up Go"
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

      
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0

    - uses: azure/setup-kubectl@v3
      name: Install kubectl
      
    - name: Run test setup script
      run: ./test/test_setup.sh
      shell: bash

    - name: Run test script
      run: ./test/test.sh
      shell: bash

    - name: Check test result
      run: ./test/test_check.sh
      shell: bash